kind: pipeline
name: default
steps:
# 代码分析
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

# 测试
- name: test
  image: python:3
  commands:
    - pip install -r requirements.txt
    - pytest

# 构建代码docker镜像
- name: code-build
  image: plugins/docker
  settings:
    registry:
      from_secret: docker_registry
    repo:
      from_secret: docker_repo
    username:
      from_secret: docker_name
    password:
      from_secret: docker_password
    tags:
      - latest
      - '1.0'


# 将部署文件放入指定目录
- name: code-scp
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    port: 22
    password:
      from_secret: ssh_password
    target: /projects/ci_test
    source: docker-compose.yaml


# 部署项目
- name: code-deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_host
    username:
      from_secret: ssh_user
    port: 22
    password:
      from_secret: ssh_password
    script:
      - cd /projects/ci_test
      - docker-compose up -d